@baseUrl = http://localhost:5000
@study = cmgu5mynd000eultc1yowvf4d
@point = 100

### 포인트 저장 테스트
POST {{baseUrl}}/study/{{study}}/point
Content-Type: application/json

{
  "point": {{point}}
}

### 스터디 정보(포인트 포함) 조회
GET {{baseUrl}}/study/{{study}}
Accept: application/json


